language: python
python:
  - "2.7"
services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - export TAG=ckan-env:$TRAVIS_BRANCH
      - docker build -t $DOCKER_USERNAME/$TAG .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        - docker push $DOCKER_USERNAME/$TAG