language: python
python:
  - "2.7"
services:
  - docker
script:
  - ./build.sh 

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$